version: "3"
services:
  api:
    build: ./api
    ports:
      - "9000:9000"
    networks:
      - cochlear
  
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - cochlear

networks:
  cochlear: