version: "2"
services:
  api:
    build: ./api
    ports:
      - "9000:9000"
    environment:
      - PORT=9000
  
  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - api
